baseURL = "http://example.org/"
languageCode = "ja-jp"
title = "Experimental Knowledge"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "description is here."
  facebook = ""
  twitter = "https://twitter.com/ttyanimal"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  body_classes = "avenir bg-near-white"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2